name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t otkmob/orders .
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push otkmob/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save f4d2b8aa-c3e3-4387-aacd-a84a72ec6f1d
      - run: kubectl rollout restart deployment orders-depl
